language: go

sudo: false

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - master

before_install:
  - go get github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - uniname --md5 LICENSE.md
  - uniname --sha1 LICENSE.md
  - uniname --sha256 LICENSE.md
  - uniname -r --sha512 LICENSE.md
